token: DSJKFKLSFJSAKLFJkjdsfksdfjISJSDLFJ93842374hAHJSDFHDSAJFjkHJDSKDASFJDFH
STATIC_DIR: ./static/
VID_PATH: ./static/downloaded_video/
AUD_PATH: ./static/downloaded_audio/
DEBUG_PORT: 8080
PROD_PORT: 80